# Site settings
title: Terms and Truth-Conditions
author: Michael Peyton Jones
email: michaelpj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Michael Peyton Jones' blog - mathematics, computer
  science, philosophy
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "https://www.michaelpj.com/blog" # the base hostname & protocol for your site
more: "More"
excerpt_separator: "<!-- more -->"
paginate: 5

twitter_username: mpeytonjones
github_username:  michaelpj
disqus_username: termsandtruthconditions
links:
  - github: "https://github.com/michaelpj/"
  - twitter: "https://twitter.com/mpeytonjones/"

# markdown settings
markdown: redcarpet

redcarpet:
  extensions: [ "footnotes" ]

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
