# Site settings
title: Terms and Truth-Conditions
author: Michael Peyton Jones
email: me@michaelpj.com
description: > # this means to ignore newlines until "baseurl:"
  Michael Peyton Jones' blog - mathematics, computer science, philosophy.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "https://www.michaelpj.com" # the base hostname & protocol for your site

# locale
lang: en-GB
timezone: Europe/London

# build settings
exclude: 
  - default.nix
  - gemset.nix
  - result
  - update-gems.sh
  - Gemfile
  - Gemfile.lock
  - README.md
strict_front_matter: true
redcarpet:
  extensions: [ "footnotes", "tables" ]
more: "More"
excerpt_separator: "<!-- more -->"
comments: true

theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  sort_reverse: true
  per_page: 5
  permalink: /posts/:num/

jekyll-archives:
  enabled:
    - tags
    - year
    - month
  layout: type_archive
  permalinks:
    tag: /archive/tag/:name/  
    year: /archive/:year/
    month: /archive/:year/:month/

twitter_username: mpeytonjones
github_username:  michaelpj
disqus:
  shortname: termsandtruthconditions
google_analytics: UA-111869417-1
