# Site settings
title: Terms and Truth-Conditions
author: Michael Peyton Jones
email: me@michaelpj.com
description: > # this means to ignore newlines until "baseurl:"
  Michael Peyton Jones' blog - mathematics, computer
  science, philosophy
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.michaelpj.com" # the base hostname & protocol for your site

theme: minima

more: "More"
excerpt_separator: "<!-- more -->"

paginate: 5

exclude: [ build, .well-known ]

twitter_username: mpeytonjones
github_username:  michaelpj
disqus_username: termsandtruthconditions
links:
  - github: "https://github.com/michaelpj/"
  - twitter: "https://twitter.com/mpeytonjones/"
  - rss: "/blog/feed.xml"

# markdown settings
redcarpet:
  extensions: [ "footnotes", "tables" ]

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
